test('First test ', () => {
  throw new Error('There is an error');
});
